variables:
  MY_NAME: ivan-ivan # Change it accordingly, please respect the formatting !

stages:
  - lint
  - test

default:
  image: 766369807176.dkr.ecr.us-east-1.amazonaws.com/node:10-alpine
  tags:
    - kubernetes 
    - rezel
    
lint-job:
  stage: lint
  script:
    - npm install
    - npm run lint

test-job:
  stage: test
  script:
    - npm install
    - npm run test
