variables:
  MY_NAME: ivan-ivan # Change it accordingly, please respect the formatting !
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
  # This variable is an exception, as it will take the value of the shortened current commit SHA, see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  APP_VERSION: ${CI_COMMIT_SHORT_SHA}

stages:
  - lint
  - test
  - test-e2e
  - build-and-release

default:
  image: 766369807176.dkr.ecr.us-east-1.amazonaws.com/node:10-alpine
  tags:
    - kubernetes 
    - rezel

lint-job:
  stage: lint
  script:
    - npm install
    - npm run lint

test-job:
  stage: test
  script:
    - npm install
    - npm run test

e2e-test-job:
  stage: test-e2e
  script:
    - npm install
    - npm run test:e2e

build-and-release-job:
  stage: build-and-release
  image: docker:20.10.16
  before_script:
    - apk add aws-cli
  script:
    - docker build -t dojo-express-app:${MY_NAME}.${APP_VERSION}
    - docker tag dojo-express-app:${MY_NAME}.${APP_VERSION} 766369807176.dkr.ecr.us-east-1.amazonaws.com/dojo-express-app:${MY_NAME}.${APP_VERSION}
    - aws ecr get-login-password | docker login --username AWS --password-stdin 766369807176.dkr.ecr.us-east-1.amazonaws.com
    - docker push 766369807176.dkr.ecr.us-east-1.amazonaws.com/dojo-express-app:${MY_NAME}.${APP_VERSION}